# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc4d0a902c61f2977d2530c00bd98b741e23d7130a13a303eafa44a2c0d02a7d30d0a2e1323c2bd6f23c59c5672447d14ce72146e1782fb027b5ab590298cf60

test:
  secret_key_base: 123c82be197e4742153ded30c3874c0d09d8da80317cba26ee331b67722babbe1a424eacdde7f40e015fdbcede3ecf7b7672321cf9ea45d6ae137e6fae6f8717

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
